### ISSUE TITLE
Reproduce paper

### ISSUE THREAD

**Issue by JaroCamphuijsen** [sunsistemo/mozzacella-automato-salad#1]
Implement 1D cellular automaton and reproduce [Wolfram paper ](http://www.stephenwolfram.com/publications/academic/random-sequence-generation-cellular-automata.pdf) as a first exploratory step.

**Comment by rahiel** [comment]
Better scan of paper: http://www.sciencedirect.com/science/article/pii/019688588690028X

**Comment by JaroCamphuijsen** [comment]
Closed by Rahiel and Martijn by implementing rule 30 again and testing for uniformness in 1fa76cb52cc15c649e0318b7bb4d98196b97a00e.
